export { default as BrowserRouter } from './BrowserRouter'
export { default as Route } from '../my-router/Route'
export { default as Switch } from '../my-router/Switch'
export { default as withRouter } from '../my-router/withRouter'
export { default as Link } from './Link'